language: java

jdk:
  - openjdk7
  - oraclejdk8


notifications:
  email:
    recipients:
      - javierparraoyola619@hotmail.com
    on_success: never
    on_failure: never

before_install:
  - mkdir target
  - cd target
  - mkdir dependency
  - cd dependency
  - curl webapp-runner.jar
  - cd ..
  - cd ..

script: 
  - cd target
  - cd dependency
  - jar cvf aplication.war
  - java -jar webapp-runner.jar aplication.war